CREATE TABLE `listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` varchar(255),
	`name` varchar(255) NOT NULL,
	`address` varchar(500),
	`city` varchar(100) NOT NULL DEFAULT 'Houston',
	`state` varchar(10) NOT NULL DEFAULT 'TX',
	`neighborhood` varchar(100),
	`minRent` int NOT NULL,
	`maxRent` int,
	`bedrooms` int,
	`bathrooms` int,
	`minSqft` int,
	`maxSqft` int,
	`builtYear` int,
	`availability` varchar(255),
	`primaryImageUrl` text,
	`imageUrls` text,
	`special` text,
	`featureHighlights` text,
	`exteriorAmenities` text,
	`interiorAmenities` text,
	`petPolicy` text,
	`managedBy` varchar(255),
	`latitude` text,
	`longitude` text,
	`isActive` int NOT NULL DEFAULT 1,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `listings_id` PRIMARY KEY(`id`)
);
